apiVersion: apps/v1
kind: Deployment
metadata:
  name: infosys-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infosys-demo
  template:
    metadata:
      labels:
        app: infosys-demo
      annotations:
        ad.datadoghq.com/nginx.logs: '[{"source":"nginx","service":"nginx"}]'
        ad.datadoghq.com/nginx.checks: |
         {
            "nginx": {
              "init_config": {},
              "instances": [
                {
                  "nginx_status_url":"http://%%host%%:81/nginx_status/"
                }
              ]
            }
          }
    spec:
      containers:
      - name: infosys-demo
        image: 471112682780.dkr.ecr.us-east-1.amazonaws.com/infosysdemo/custome-nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 81
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/status.conf
          subPath: status.conf
          readOnly: true
          name: "config"
      volumes:
      - name: "config"
        configMap:
          name: "nginx-conf"