apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  status.conf: |
    server {
      listen 81;

      location /nginx_status {
        stub_status on;
      }

      location / {
        return 404;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infosys-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infosys-demo
  template:
    metadata:
      labels:
        app: infosys-demo
        annotations:
            ad.datadoghq.com/nginx.logs: '[{"source":"nginx","service":"nginx"}]'
            ad.datadoghq.com/nginx.checks: |
            {
                "nginx": {
                  "init_config": {},
                  "instances": [
                    {
                      "nginx_status_url":"http://%%host%%:81/nginx_status/"
                    }
                  ]
                }
              }
    spec:
      containers:
      - name: infosys-demo
        image: 471112682780.dkr.ecr.us-east-1.amazonaws.com/infosysdemo/custome-nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: infosys-demo-service
spec:
  selector:
    app: infosys-demo
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer