apiVersion: apps/v1
kind: Deployment
metadata:
  name: infosys-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infosys-demo
  template:
    metadata:
      labels:
        app: infosys-demo
    spec:
      containers:
      - name: infosys-demo
        image: 471112682780.dkr.ecr.us-east-1.amazonaws.com/infosysdemo/custome-nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: infosys-demo-service
spec:
  selector:
    app: infosys-demo
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer